import { AIProcessResult } from './ai.types.js';
import { INTERACTIVE_NOT_FOUND_REPLY } from './interactive-not-found.js';
import {
  SenderLanguage,
  getLanguageSafeFallback,
  isResponseInSenderLanguage,
} from './sender-language.js';

type Replacement = readonly [string, string];

const ARABIC_REPLACEMENTS: Replacement[] = [
  ['Your order from', '\u0637\u0644\u0628\u0643 \u0645\u0646'],
  ['is currently', '\u062d\u0627\u0644\u064a\u064b\u0627'],
  ['Order #', '\u0637\u0644\u0628 #'],
  ['Delivering to', '\u0639\u0645 \u0646\u0648\u0635\u0651\u0644 \u0639\u0644\u0649'],
  ['Understood your voice shopping list! I compared nearby supermarkets:', '\u0641\u0647\u0645\u062a \u0644\u0627\u0626\u062d\u0629 \u062a\u0633\u0648\u0651\u0642\u0643 \u0627\u0644\u0635\u0648\u062a\u064a\u0629! \u0642\u0627\u0631\u0646\u062a \u0644\u0643 \u0627\u0644\u0633\u0648\u0628\u0631\u0645\u0627\u0631\u0643\u062a\u0627\u062a \u0627\u0644\u0642\u0631\u064a\u0628\u0629:'],
  ['**Best Value:', '**\u0623\u0641\u0636\u0644 \u0642\u064a\u0645\u0629:'],
  ['Total Complete Basket:', '\u0645\u062c\u0645\u0648\u0639 \u0627\u0644\u0633\u0644\u0629 \u0627\u0644\u0643\u0627\u0645\u0644:'],
  ['All ', '\u0643\u0644 '],
  [' items are in stock. Should I prepare this cart for you?', ' \u0623\u0635\u0646\u0627\u0641 \u0645\u062a\u0648\u0641\u0631\u0629. \u0628\u062f\u0643 \u062d\u0636\u0651\u0631 \u0647\u0627\u0644\u0633\u0644\u0629 \u0625\u0644\u0643\u061f'],
  ['I couldn\'t find that within my current catalog. Do you want to choose another item or try a different name?', 'ما لقيت هالشي ضمن الكاتالوغ الحالي. بدك تختار غرض تاني أو تجرّب اسم مختلف؟'],
  ['I didn\'t quite understand that. Could you clarify what you\'d like, for example: search for a product, add an item, or check your cart?', 'ما فهمت عليك تمامًا. فيك توضّح أكتر؟ مثلًا: فتّش عن غرض، ضيف غرض، أو فرجيني السلة؟'],
  ['I found multiple', 'لقيت أكتر من'],
  ['Which one should I use?', 'أي واحد استعمل؟'],
  ['Which item would you like to update to 1?', 'أي غرض بدك حدّثه ليصير 1؟'],
  ['Which item would you like to make 2?', 'أي غرض بدك خلّيه 2؟'],
  ['Do you mean the Coke or the meal?', 'قصدك الكولا أو الوجبة؟'],
  ['Please answer on the next message:', 'جاوبني بالرسالة الجاية:'],
  ['I kept your current cart.', 'خلّيت سلتك الحالية متل ما هي.'],
  ['Please explicitly confirm if you want to switch to', 'أكدلي بوضوح إذا بدك تنتقل إلى'],
  ['Done — I cleared the old cart and added the item from', 'تم — فضّيت السلة القديمة وضفت الغرض من'],
  ['Your cart is ready for review.', 'سلتك جاهزة للمراجعة.'],
  ['Your cart already has items from', 'سلتك فيها أغراض من'],
  ['Clear it and switch to', 'نفضّيها وننتقل إلى'],
  ['Please reply "yes" or "confirm" if you want to switch.', 'ردّ "yes" أو "confirm" إذا بدك ننتقل.'],
  ['Added', 'ضفت'],
  ['Updated', 'حدّثت'],
  ['Updated!', 'تحدّثت السلة!'],
  ['Got it!', 'تمام!'],
  ['Done!', 'تم!'],
  ['Removed', 'شلت'],
  ['from your cart', 'من سلتك'],
  ['to your cart', 'على سلتك'],
  ['from', 'من'],
  ['Your cart total is', 'مجموع سلتك هو'],
  ['New total:', 'المجموع الجديد:'],
  ['Cart Subtotal:', 'المجموع الفرعي للسلة:'],
  ['Delivery Fee:', 'رسم التوصيل:'],
  ['Delivery:', 'التوصيل:'],
  ['Subtotal:', 'المجموع الفرعي:'],
  ['Cash on Delivery', 'الدفع عند الاستلام'],
  ['Final Order Summary', 'ملخص الطلب النهائي'],
  ['Reply **"confirm"** to place your order!', 'ردّ **"confirm"** لتأكيد طلبك!'],
  ['Ready to checkout, or would you like anything else?', 'السلة جاهزة للتأكيد، أو بدك تضيف شي تاني؟'],
  ['Anything else you\'d like to add?', 'بدك تضيف شي تاني؟'],
  ['Would you like me to add it to your cart?', 'بدك ضيفه على سلتك؟'],
  ['Shall I add this to your cart?', 'بدك ضيفه على سلتك؟'],
  ['Would you like me to add it?', 'بدك ضيفه؟'],
  ['Please select an address and review the final order summary before confirming.', 'اختار عنوان وراجع ملخص الطلب النهائي قبل التأكيد.'],
  ['I will only place the order after a clear confirmation such as "confirm".', 'ما رح حط الطلب إلا بعد تأكيد واضح مثل "confirm".'],
  ['Your cart is currently empty! What would you like to order?', 'سلتك فاضية حاليًا! شو بتحب تطلب؟'],
  ['This order was already confirmed', 'هالطلب متأكد من قبل'],
  ['Your cart or checkout details changed. I need to show you a fresh final summary before placing the order.', 'تغيّرت السلة أو تفاصيل الدفع. لازم فرجيك ملخص نهائي جديد قبل وضع الطلب.'],
  ['Found great burger options under $15 for you in Saida:', 'لقيتلك خيارات برغر حلوة تحت $15 بصيدا:'],
  ['Found great crispy chicken options under $15 for you in Saida:', 'لقيتلك خيارات دجاج مقرمش حلوة تحت $15 بصيدا:'],
  ['You can ask me follow-up questions', 'فيني جاوبك على أسئلة إضافية'],
  ['You can ask me follow-up questions like', 'فيني جاوبك على أسئلة إضافية مثل'],
  ['or simply tell me', 'أو خبرني ببساطة'],
  ['Which one did you mean?', 'أي واحد قصدت؟'],
  ['Reply with 1, 2, or 3.', 'ردّ برقم 1 أو 2 أو 3.'],
  ['I can also use a number', 'فيني استعمل رقم'],
  ['or a neighborhood name.', 'أو اسم منطقة.'],
  ['I don\'t quite understand that.', 'ما فهمت عليك.'],
  ['Would you like to order something delicious?', 'بدك تطلب شي طيب؟'],
  ['Hello!', 'مرحبًا!'],
  ['Welcome to **Lion Delivery**!', 'أهلًا فيك بـ **Lion Delivery**!'],
  ['I\'m your AI assistant.', 'أنا مساعدك الذكي.'],
  ['What would you like to eat today?', 'شو بتحب تاكل اليوم؟'],
  ['Order Confirmed!', 'تم تأكيد الطلب!'],
  ['Merchant:', 'المطعم:'],
  ['Items:', 'الأغراض:'],
  ['Total to Pay (Cash):', 'المجموع للدفع نقدًا:'],
  ['Delivering To:', 'التوصيل إلى:'],
  ['Estimated Delivery:', 'وقت التوصيل المتوقع:'],
  ['The restaurant is reviewing your order now.', 'المطعم عم يراجع طلبك هلّق.'],
  ['You will receive live status updates right here!', 'رح توصلك تحديثات الحالة هون مباشرة!'],
  ['Your order from', 'طلبك من'],
  ['is currently', 'حاليًا'],
  ['You don\'t have any active deliveries right now.', 'ما عندك توصيلات نشطة حاليًا.'],
  ['Customer Care', 'خدمة الزبائن'],
  ['Update', 'تحديث'],
  ['Total:', 'المجموع:'],
  ['Estimated arrival in approximately', 'الوصول المتوقع خلال حوالي'],
  ['minutes!', 'دقيقة!'],
  ['I found a few possible matches in our catalog:', 'لقيت كم احتمال بكتالوغنا:'],
  ['Yes! ', 'إيه! '],
  [' has this item:', ' عنده هالغرض:'],
  ['The most affordable crispy meal is at', 'أرخص وجبة مقرمشة موجودة عند'],
  ['Best dessert options under $3:', 'أطيب خيارات حلو تحت $3:'],
  ['Best dessert options with great prices:', 'أطيب خيارات حلو وأسعارها مناسبة:'],
  ['Which option would you like me to add?', 'أي خيار بدك ضيفه؟'],
  ['address (', ' عنوان ('],
  ['I\'ve flagged your request', 'سجّلت طلبك'],
  ['An agent can join this chat shortly.', 'رح ينضم موظف لهالمحادثة قريبًا.'],
  ['your **', 'عنوانك **'],
  ['I\'ve flagged your request for our Saida operations dispatch team.', 'سجّلت طلبك لفريق العمليات في صيدا.'],
  ['An agent can join this chat shortly.', 'رح ينضم موظف لهالمحادثة قريبًا.'],
  ['items from', 'أغراض من'],
  ['delivery =', 'توصيل ='],
  ['delivery', 'التوصيل'],
];

const ARABIZI_REPLACEMENTS: Replacement[] = [
  ['Your order from', 'Talabak men'],
  ['is currently', 'halla2 7aletou'],
  ['Order #', 'Talab #'],
  ['Delivering to', '3am noussal 3a'],
  ['Understood your voice shopping list! I compared nearby supermarkets:', 'Fhemet listet l shopping taba3ak! 2arantlak l supermarkets l 2rabin:'],
  ['**Best Value:', '**A7san 2ime:'],
  ['Total Complete Basket:', 'Majmou3 l basket kello:'],
  ['All ', 'Kel '],
  [' items are in stock. Should I prepare this cart for you?', ' items mawjoude. Baddak 7adder hal cart la2elak?'],
  ['I couldn\'t find that within my current catalog. Do you want to choose another item or try a different name?', 'Ma la2ayt hal shi bi catalog taba3e l7ale. Baddak tkhtar shi tene aw tjarrib esem tene?'],
  ['I didn\'t quite understand that. Could you clarify what you\'d like, for example: search for a product, add an item, or check your cart?', 'Ma fhemet 3layk ktir. Fik teshra7 aktar? Masalan: ftteish 3a shi, zid item, aw shouf el cart?'],
  ['I found multiple', 'La2ayt aktar men'],
  ['Which one should I use?', 'Ayya we7de esta3mel?'],
  ['Which item would you like to update to 1?', 'Ayya item baddak t5alleh yseer 1?'],
  ['Which item would you like to make 2?', 'Ayya item baddak tsawiyo 2?'],
  ['Do you mean the Coke or the meal?', '2asdak el Coke aw el meal?'],
  ['Please answer on the next message:', 'Jawibne bel message l jeye:'],
  ['I kept your current cart.', 'Khalleit el cart taba3ak metel ma hiyye.'],
  ['Please explicitly confirm if you want to switch to', '2akkedle wade7 iza baddak tent2el 3a'],
  ['Done — I cleared the old cart and added the item from', 'Tamam — farraghet el cart l2dime w zedt el item men'],
  ['Your cart is ready for review.', 'El cart taba3ak jahiz lal review.'],
  ['Your cart already has items from', 'El cart taba3ak fiya items men'],
  ['Clear it and switch to', 'Nfaddiya w nent2el 3a'],
  ['Please reply "yes" or "confirm" if you want to switch.', 'Rodd "yes" aw "confirm" iza baddak nent2el.'],
  ['Added', 'Zedt'],
  ['Updated', '3addalet'],
  ['Updated!', '3addalet el cart!'],
  ['Got it!', 'Tamam!'],
  ['Done!', 'Tamam!'],
  ['Removed', 'Shelt'],
  ['from your cart', 'men el cart taba3ak'],
  ['to your cart', '3a el cart taba3ak'],
  ['from', 'men'],
  ['Your cart total is', 'Majmou3 el cart taba3ak sar'],
  ['New total:', 'El majmou3 l jdid:'],
  ['Cart Subtotal:', 'Majmou3 el cart:'],
  ['Delivery Fee:', 'Rsem el delivery:'],
  ['Delivery:', 'Delivery:'],
  ['Subtotal:', 'El majmou3 l fare3e:'],
  ['Cash on Delivery', 'Cash 3al delivery'],
  ['Final Order Summary', 'Molakhas el talab l nehe2e'],
  ['Reply **"confirm"** to place your order!', 'Rodd **"confirm"** ta n2akked el talab!'],
  ['Ready to checkout, or would you like anything else?', 'Jahzin lal checkout, aw baddak shi tene?'],
  ['Anything else you\'d like to add?', 'Baddak tzid shi tene?'],
  ['Would you like me to add it to your cart?', 'Baddak zido 3a el cart?'],
  ['Shall I add this to your cart?', 'Zido 3a el cart?'],
  ['Would you like me to add it?', 'Baddak zido?'],
  ['Please select an address and review the final order summary before confirming.', 'Ekhtar address w raje3 molakhas el talab l nehe2e abel ma t2akked.'],
  ['I will only place the order after a clear confirmation such as "confirm".', 'Ma ra7 7ott el talab ella ba3d ta2kid wade7 metel "confirm".'],
  ['Your cart is currently empty! What would you like to order?', 'El cart fadi halla2! Shou baddak tetlob?'],
  ['This order was already confirmed', 'Hal talab t2akkad men abel'],
  ['Your cart or checkout details changed. I need to show you a fresh final summary before placing the order.', 'Tghayyar el cart aw tafasil el checkout. Lazem farjik molakhas jdid abel ma 7ott el talab.'],
  ['Found great burger options under $15 for you in Saida:', 'La2ayt options burger kteer 7elwe ta7et $15 bi Saida:'],
  ['Found great crispy chicken options under $15 for you in Saida:', 'La2ayt options crispy chicken 7elwe ta7et $15 bi Saida:'],
  ['You can ask me follow-up questions', 'Fik tes2alne as2ile zeyde'],
  ['You can ask me follow-up questions like', 'Fik tes2alne as2ile zeyde metel'],
  ['or simply tell me', 'aw khabberne bse3a'],
  ['Which one did you mean?', 'Ayya we7de 2asdak?'],
  ['Reply with 1, 2, or 3.', 'Rodd b ra2em 1, 2, aw 3.'],
  ['I can also use a number', 'Fini esta3mel ra2em'],
  ['or a neighborhood name.', 'aw esem manta2a.'],
  ['Would you like to order something delicious?', 'Baddak tetlob shi tayyeb?'],
  ['Hello!', 'Mar7aba!'],
  ['Welcome to **Lion Delivery**!', 'Ahlan fik bi **Lion Delivery**!'],
  ['I\'m your AI assistant.', 'Ana l musa3ed taba3ak.'],
  ['What would you like to eat today?', 'Shou baddak tekol lyoum?'],
  ['Order Confirmed!', 'Talabak t2akkad!'],
  ['Merchant:', 'El mat3am:'],
  ['Items:', 'El items:'],
  ['Total to Pay (Cash):', 'El majmou3 lal daf3 cash:'],
  ['Delivering To:', '3am noussal 3a:'],
  ['Estimated Delivery:', 'W2et el delivery l motawa2a3:'],
  ['The restaurant is reviewing your order now.', 'El mat3am 3am yraje3 talabak halla2.'],
  ['You will receive live status updates right here!', 'Ra7 yousalak updates 3an el status hawn mobashara!'],
  ['You don\'t have any active deliveries right now.', 'Ma 3andak deliveries neshta halla2.'],
  ['Customer Care', 'Khedmet l zaba2en'],
  ['Update', 'Update'],
  ['Total:', 'El majmou3:'],
  ['Estimated arrival in approximately', 'El wosoul l motawa2a3 ba3d ta2riban'],
  ['minutes!', ' da2i2a!'],
  ['I found a few possible matches in our catalog:', 'La2ayt kam e7timel bi catalog taba3na:'],
  ['Yes! ', 'Eh! '],
  [' has this item:', ' 3ando hal item:'],
  ['The most affordable crispy meal is at', 'Ar5as crispy meal 3end'],
  ['Best dessert options under $3:', 'A7la options 7elo ta7et $3:'],
  ['Best dessert options with great prices:', 'A7la options 7elo w se3ra 7elwe:'],
  ['Which option would you like me to add?', 'Ayya option baddak zido?'],
  ['address (', ' address ('],
];

const FRENCH_REPLACEMENTS: Replacement[] = [
  ['Your order from', 'Votre commande de'],
  ['is currently', 'est actuellement'],
  ['Order #', 'Commande n°'],
  ['Delivering to', 'Livraison à'],
  ['Understood your voice shopping list! I compared nearby supermarkets:', 'J’ai compris votre liste vocale ! J’ai compare les supermarches a proximite :'],
  ['**Best Value:', '**Meilleur rapport qualite-prix :'],
  ['Total Complete Basket:', 'Total du panier complet :'],
  ['All ', 'Tous les '],
  [' items are in stock. Should I prepare this cart for you?', ' articles sont disponibles. Dois-je preparer ce panier pour vous ?'],
  ['I couldn\'t find that within my current catalog. Do you want to choose another item or try a different name?', 'Je ne trouve pas cela dans mon catalogue actuel. Voulez-vous choisir un autre article ou essayer un autre nom ?'],
  ['I didn\'t quite understand that. Could you clarify what you\'d like, for example: search for a product, add an item, or check your cart?', 'Je n’ai pas bien compris. Pouvez-vous préciser, par exemple : rechercher un article, en ajouter un ou consulter votre panier ?'],
  ['I found multiple', 'J’ai trouvé plusieurs'],
  ['Which one should I use?', 'Lequel dois-je utiliser ?'],
  ['Which item would you like to update to 1?', 'Quel article voulez-vous mettre à 1 ?'],
  ['Which item would you like to make 2?', 'Quel article voulez-vous mettre à 2 ?'],
  ['Do you mean the Coke or the meal?', 'Parlez-vous du Coca ou du repas ?'],
  ['Please answer on the next message:', 'Répondez au prochain message :'],
  ['I kept your current cart.', 'J’ai conservé votre panier actuel.'],
  ['Please explicitly confirm if you want to switch to', 'Confirmez clairement si vous souhaitez passer à'],
  ['Done — I cleared the old cart and added the item from', 'C’est fait — j’ai vidé l’ancien panier et ajouté l’article de'],
  ['Your cart is ready for review.', 'Votre panier est prêt à être vérifié.'],
  ['Your cart already has items from', 'Votre panier contient déjà des articles de'],
  ['Clear it and switch to', 'Le vider et passer à'],
  ['Please reply "yes" or "confirm" if you want to switch.', 'Répondez « yes » ou « confirm » pour changer.'],
  ['Added', 'Ajouté'],
  ['Updated', 'Mis à jour'],
  ['Updated!', 'Panier mis à jour !'],
  ['Got it!', 'Compris !'],
  ['Done!', 'C’est fait !'],
  ['Removed', 'Retiré'],
  ['from your cart', 'de votre panier'],
  ['to your cart', 'à votre panier'],
  ['from', 'de'],
  ['Your cart total is', 'Le total de votre panier est'],
  ['New total:', 'Nouveau total :'],
  ['Cart Subtotal:', 'Sous-total du panier :'],
  ['Delivery Fee:', 'Frais de livraison :'],
  ['Delivery:', 'Livraison :'],
  ['Subtotal:', 'Sous-total :'],
  ['Cash on Delivery', 'Paiement à la livraison'],
  ['Final Order Summary', 'Résumé final de la commande'],
  ['Reply **"confirm"** to place your order!', 'Répondez **« confirm »** pour passer la commande !'],
  ['Ready to checkout, or would you like anything else?', 'Prêt à confirmer, ou souhaitez-vous ajouter autre chose ?'],
  ['Anything else you\'d like to add?', 'Voulez-vous ajouter autre chose ?'],
  ['Would you like me to add it to your cart?', 'Voulez-vous que je l’ajoute à votre panier ?'],
  ['Shall I add this to your cart?', 'Je l’ajoute à votre panier ?'],
  ['Would you like me to add it?', 'Voulez-vous que je l’ajoute ?'],
  ['Please select an address and review the final order summary before confirming.', 'Sélectionnez une adresse et vérifiez le résumé final avant de confirmer.'],
  ['I will only place the order after a clear confirmation such as "confirm".', 'Je passerai la commande uniquement après une confirmation claire comme « confirm ».'],
  ['Your cart is currently empty! What would you like to order?', 'Votre panier est vide ! Que souhaitez-vous commander ?'],
  ['This order was already confirmed', 'Cette commande a déjà été confirmée'],
  ['Your cart or checkout details changed. I need to show you a fresh final summary before placing the order.', 'Le panier ou les détails ont changé. Je dois vous montrer un nouveau résumé final avant de passer la commande.'],
  ['Found great burger options under $15 for you in Saida:', 'Voici de bonnes options de burgers à moins de 15 $ à Saïda :'],
  ['Found great crispy chicken options under $15 for you in Saida:', 'Voici de bonnes options de poulet croustillant à moins de 15 $ à Saïda :'],
  ['You can ask me follow-up questions', 'Vous pouvez poser des questions supplémentaires'],
  ['You can ask me follow-up questions like', 'Vous pouvez poser des questions comme'],
  ['Which one did you mean?', 'Lequel vouliez-vous dire ?'],
  ['Reply with 1, 2, or 3.', 'Répondez par 1, 2 ou 3.'],
  ['I can also use a number', 'Vous pouvez aussi donner un numéro'],
  ['or a neighborhood name.', 'ou le nom d’un quartier.'],
  ['Would you like to order something delicious?', 'Voulez-vous commander quelque chose de bon ?'],
  ['Hello!', 'Bonjour !'],
  ['Welcome to **Lion Delivery**!', 'Bienvenue chez **Lion Delivery** !'],
  ['I\'m your AI assistant.', 'Je suis votre assistant IA.'],
  ['What would you like to eat today?', 'Que souhaitez-vous manger aujourd’hui ?'],
  ['Order Confirmed!', 'Commande confirmée !'],
  ['Merchant:', 'Restaurant :'],
  ['Items:', 'Articles :'],
  ['Total to Pay (Cash):', 'Total à payer (espèces) :'],
  ['Delivering To:', 'Livraison à :'],
  ['Estimated Delivery:', 'Livraison estimée :'],
  ['The restaurant is reviewing your order now.', 'Le restaurant examine votre commande.'],
  ['You will receive live status updates right here!', 'Vous recevrez les mises à jour ici même !'],
  ['You don\'t have any active deliveries right now.', 'Vous n’avez aucune livraison active pour le moment.'],
  ['Customer Care', 'Service client'],
  ['Update', 'Mise à jour'],
  ['Total:', 'Total :'],
  ['Estimated arrival in approximately', 'Arrivée estimée dans environ'],
  ['minutes!', 'minutes !'],
  ['I found a few possible matches in our catalog:', 'J’ai trouvé quelques possibilités dans notre catalogue :'],
  ['Yes! ', 'Oui ! '],
  [' has this item:', ' propose cet article :'],
  ['The most affordable crispy meal is at', 'Le repas croustillant le moins cher est chez'],
  ['Best dessert options under $3:', 'Meilleures options sucrées à moins de 3 $ :'],
  ['Best dessert options with great prices:', 'Meilleures options sucrées à bon prix :'],
  ['Which option would you like me to add?', 'Quelle option souhaitez-vous que j’ajoute ?'],
  ['address (', ' adresse ('],
];

function replaceAll(text: string, replacements: Replacement[]): string {
  return replacements.reduce((current, [from, to]) => current.split(from).join(to), text);
}

function replacementsFor(language: SenderLanguage): Replacement[] {
  if (language === 'ar' || language === 'ar_lb' || language === 'mixed') return ARABIC_REPLACEMENTS;
  if (language === 'arabizi') return ARABIZI_REPLACEMENTS;
  if (language === 'fr') return FRENCH_REPLACEMENTS;
  return [];
}

/**
 * Localizes deterministic Smart NLU and safety copy while preserving catalog
 * names, merchant names, quantities, prices, order IDs, and WhatsApp markup.
 */
export function localizeReplyText(text: string, language: SenderLanguage): string {
  if (!text) return getLanguageSafeFallback(language);

  let localized = text;
  if (localized.includes(INTERACTIVE_NOT_FOUND_REPLY)) {
    localized = localized.replace(
      INTERACTIVE_NOT_FOUND_REPLY,
      replacementsFor(language).find(([from]) => from === INTERACTIVE_NOT_FOUND_REPLY)?.[1] || INTERACTIVE_NOT_FOUND_REPLY,
    );
  }
  localized = replaceAll(localized, replacementsFor(language).filter(([from]) => from !== INTERACTIVE_NOT_FOUND_REPLY));

  if (language !== 'en' && !isResponseInSenderLanguage(language, localized)) {
    return getLanguageSafeFallback(language);
  }
  return localized;
}

export function localizeSmartNluResult(result: AIProcessResult, language: SenderLanguage): AIProcessResult {
  return {
    ...result,
    replyText: localizeReplyText(result.replyText, language),
  };
}
